<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="3" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite2" duration-ms="15734" started-at="2018-09-11T11:30:57Z" finished-at="2018-09-11T11:31:13Z">
    <groups>
    </groups>
    <test name="test" duration-ms="15734" started-at="2018-09-11T11:30:57Z" finished-at="2018-09-11T11:31:13Z">
      <class name="com.liuchao.testcase.LoginTest">
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String)[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="beforeClass" is-config="true" duration-ms="9361" started-at="2018-09-11T19:30:57Z" finished-at="2018-09-11T19:31:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[D:\eclipse-workspace\WebUITest\driver\chromedriver.exe]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[http://stage.mes.edianzu.cn/login.jsp]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="BeforeMethod" is-config="true" duration-ms="2" started-at="2018-09-11T19:31:06Z" finished-at="2018-09-11T19:31:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="login02(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="login02" duration-ms="1740" started-at="2018-09-11T19:31:06Z" description="异常用户信息登录" data-provider="loginParams" finished-at="2018-09-11T19:31:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[li]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名或密码错误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [用户名或密码错误] but found [用户名或密码有误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [用户名或密码错误] but found [用户名或密码有误]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.liuchao.testcase.LoginTest.login02(LoginTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login02 -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="BeforeMethod" is-config="true" duration-ms="1" started-at="2018-09-11T19:31:08Z" finished-at="2018-09-11T19:31:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="login02(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="login02" duration-ms="1321" started-at="2018-09-11T19:31:08Z" description="异常用户信息登录" data-provider="loginParams" finished-at="2018-09-11T19:31:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[li]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名或密码错误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [用户名或密码错误] but found [用户名或密码有误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [用户名或密码错误] but found [用户名或密码有误]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.liuchao.testcase.LoginTest.login02(LoginTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login02 -->
        <test-method status="PASS" signature="BeforeMethod()[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="BeforeMethod" is-config="true" duration-ms="0" started-at="2018-09-11T19:31:10Z" finished-at="2018-09-11T19:31:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method status="FAIL" signature="login02(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="login02" duration-ms="1305" started-at="2018-09-11T19:31:10Z" description="异常用户信息登录" data-provider="loginParams" finished-at="2018-09-11T19:31:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[123456]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[用户名或密码错误]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [用户名或密码错误] but found [用户名或密码有误]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [用户名或密码错误] but found [用户名或密码有误]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.liuchao.testcase.LoginTest.login02(LoginTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login02 -->
        <test-method status="SKIP" signature="login(java.lang.String, java.lang.String)[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="login" duration-ms="0" started-at="2018-09-11T19:31:11Z" description="正常用户登录" depends-on-methods="com.liuchao.testcase.LoginTest.login02" finished-at="2018-09-11T19:31:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="afterClass" is-config="true" duration-ms="1" started-at="2018-09-11T19:31:11Z" finished-at="2018-09-11T19:31:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.liuchao.testcase.LoginTest@7c75222b]" name="afterTest" is-config="true" duration-ms="1076" started-at="2018-09-11T19:31:11Z" finished-at="2018-09-11T19:31:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.liuchao.testcase.LoginTest -->
    </test> <!-- test -->
  </suite> <!-- Suite2 -->
</testng-results>
